#!/bin/bash

APPDIR=../www/less
WEBDIR=../../web/static/less

find $APPDIR/src/ -name '*.less' -exec lessc {} \; > $APPDIR/lib/app.css
find $WEBDIR/src/ -name '*.less' -exec lessc {} \; > $WEBDIR/lib/web.css
